### ISSUE TITLE
Forgotten passwords can't be recovered

### ISSUE THREAD

**Issue by courte** [CodeMontageHQ/codemontage#303]
**Description**
The very mysterious 

![screenshot 2015-01-12 15 19 21](https://cloud.githubusercontent.com/assets/2766324/5710259/9a3b9e24-9a6e-11e4-9a63-f8e23138d9d6.png)

appears when trying to retrieve a forgotten password.

**Ask**
Fix the bug that's causing POST `/auth/password` requests to fail.

**To Do**
- [x] Determine what is causing POST requests to `/auth/password` to return a 500 server error.
- [x] Fix the problem.

**Additional Info**
We are using Devise for user authentication.

**Comment by thefenry** [comment]
@courte Has this been fixed? It seems to be working on the deployed site and on the source code for me.

**Comment by courte** [comment]
Can you tell me what process you're using, @thefenry? I'm still getting status 500 when I log out and try to recover my password.

**Comment by thefenry** [comment]
Hey @courte, 
I know it does not work on the deployed code but on my local instance I have clicked on login and immediately select forgot password when the page loads. I then enter my email and select the "send me password reset instructions" button which then gives me an alert "You will receive an email with instructions about how to reset your password in a few minutes.". 
I also tried to login and out and then doing the reset password again. It "worked". I am wondering if the reason it is not crashing on me is because I do not have the actual mailing service active? I think this is done through the devise gem. 
:confounded:

**Comment by SojournerOctocat** [comment]
This is still an ongoing issue. I am not able to recover my password. I am taken to the https://www.codemontage.com/auth/password page with the "We're sorry…" error pictured above.

**Comment by escobara** [comment]
I think the problem occurs because it doesn't appear that ActionMailer is setup in the production environment.

**Comment by courte** [comment]
Resolved with #375 (but the saga continues with #380).
